// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMvKmBsGt9JixSSM5VbLdJtxZr5PaEYVM',
    appId: '1:707031254641:web:61cc673614d4e3f80ffdd0',
    messagingSenderId: '707031254641',
    projectId: 'idyotapp',
    authDomain: 'idyotapp.firebaseapp.com',
    storageBucket: 'idyotapp.appspot.com',
    measurementId: 'G-82BTT0PF1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGQE21wIZAe1H9HUP4mK211AMb-F0s-44',
    appId: '1:707031254641:android:5fe89d2cc00b88bd0ffdd0',
    messagingSenderId: '707031254641',
    projectId: 'idyotapp',
    storageBucket: 'idyotapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXTVCbL3UZbluFkpnmPNSdKQE2UoZRNgQ',
    appId: '1:707031254641:ios:99fb43b762ab2fed0ffdd0',
    messagingSenderId: '707031254641',
    projectId: 'idyotapp',
    storageBucket: 'idyotapp.appspot.com',
    iosClientId: '707031254641-6738p38q62q1q1s3kendb6o6p5vohtgp.apps.googleusercontent.com',
    iosBundleId: 'com.example.idiotapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXTVCbL3UZbluFkpnmPNSdKQE2UoZRNgQ',
    appId: '1:707031254641:ios:99fb43b762ab2fed0ffdd0',
    messagingSenderId: '707031254641',
    projectId: 'idyotapp',
    storageBucket: 'idyotapp.appspot.com',
    iosClientId: '707031254641-6738p38q62q1q1s3kendb6o6p5vohtgp.apps.googleusercontent.com',
    iosBundleId: 'com.example.idiotapp',
  );
}
